"use client";

import { useEffect, useMemo, useState } from "react";
import { Download, Filter, Gauge, Route, Sparkles, Tag, TrendingDown, TrendingUp } from "lucide-react";
import type { MT5Metrics, MT5ParseResult, MT5Trade } from "@/lib/mt5-parser";
import type { AdvancedAnalytics } from "@/lib/advanced-analytics";
import type { MonteCarloProjection } from "@/lib/monte-carlo";

const TAGS = ["#FOMO", "#HorsPlan", "#Breakout", "#Sur-réaction", "#PressionExecution"] as const;
type TradeTag = typeof TAGS[number];

function money(value: number) { return `${value >= 0 ? "+" : ""}${value.toLocaleString("fr-FR", { maximumFractionDigits: 0 })} $`; }
function escapeXml(value: string) { return value.replace(/[<>&'\"]/g, (char) => ({ "<": "&lt;", ">": "&gt;", "&": "&amp;", "'": "&apos;", '\"': "&quot;" }[char] ?? char)); }

export function MonteCarloPanel({ projection }: { projection: MonteCarloProjection }) {
  const probability = projection.successProbability;
  return <section className="neon-card rounded-3xl border border-sky-400/15 bg-sky-400/[0.04] p-4 sm:p-6"><div className="flex items-start justify-between gap-3"><div><div className="flex items-center gap-2 text-sm font-semibold text-white"><Gauge className="h-4 w-4 text-sky-300" /> Simulateur Monte-Carlo</div><p className="mt-1 text-xs text-zinc-500">1 000 trajectoires statistiques à partir de votre Win Rate et Risk:Reward réels.</p></div><span className="rounded-full border border-sky-300/20 bg-sky-300/10 px-2 py-1 text-[10px] font-semibold text-sky-200">100 trades</span></div><div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-4"><Metric label="Probabilité positive" value={`${probability.toFixed(1)}%`} tone={probability >= 50 ? "text-emerald-300" : "text-amber-300"} /><Metric label="PnL médian" value={money(projection.medianReturn)} /><Metric label="DD médian" value={money(-projection.medianDrawdown)} tone="text-rose-300" /><Metric label="DD P90" value={money(-projection.p90Drawdown)} tone="text-rose-300" /></div><div className="mt-5 h-2 overflow-hidden rounded-full bg-white/10"><div className={`h-full rounded-full ${probability >= 50 ? "bg-emerald-400" : "bg-amber-400"}`} style={{ width: `${Math.min(100, Math.max(0, probability))}%` }} /></div><p className="mt-3 text-xs leading-5 text-zinc-500">Projection indicative : elle suppose que la distribution historique reste stable et ne remplace pas une validation de risque.</p></section>;
}
function Metric({ label, value, tone = "text-white" }: { label: string; value: string; tone?: string }) { return <div className="rounded-2xl border border-white/[0.07] bg-black/20 p-3"><p className="text-[10px] uppercase tracking-wider text-zinc-600">{label}</p><p className={`mt-2 text-base font-semibold ${tone}`}>{value}</p></div>; }

export function StrategyRoadmap({ result, metrics, advanced }: { result: MT5ParseResult; metrics: MT5Metrics; advanced: AdvancedAnalytics }) {
  const [macro, setMacro] = useState<{ title: string; currency?: string; impact?: string } | null>(null);
  useEffect(() => { let active = true; fetch("/api/macro-news", { cache: "no-store" }).then((response) => response.ok ? response.json() : null).then((data) => { if (active) setMacro(data?.calendar?.[0] ?? data?.articles?.[0] ?? null); }).catch(() => undefined); return () => { active = false; }; }, []);
  const targetPair = result.metrics.symbolsTraded[0] ?? "l'actif ciblé";
  const firstPrice = result.trades[0]?.price ?? 0;
  const lastPrice = result.trades[result.trades.length - 1]?.price ?? firstPrice;
  const technicalBias = lastPrice > firstPrice ? "biais haussier" : lastPrice < firstPrice ? "biais baissier" : "structure neutre";
  const history = result.trades.filter((trade) => trade.symbol === targetPair);
  const pairWinRate = history.length ? history.filter((trade) => trade.profit > 0).length / history.length * 100 : 0;
  const bestSession = advanced.heatmap.length ? "la session présentant votre meilleure espérance historique" : "la session correspondant à votre plan écrit";
  const fundamentalText = macro ? `${macro.title}${macro.currency ? ` · ${macro.currency}` : ""}${macro.impact ? ` · impact ${macro.impact}` : ""}. Vérifiez le calendrier avant toute exécution.` : "Aucun événement live disponible : restez en mode observation jusqu'à la prochaine mise à jour.";
  const technicalText = `${targetPair} montre une ${technicalBias} selon l'évolution des prix importés. Validez les niveaux clés et n'exécutez qu'après confirmation de clôture.`;
  const historyText = `Sur ${targetPair}, votre taux de réussite historique est de ${pairWinRate.toFixed(1)}%. Travaillez ${bestSession} et réduisez l'exposition si le drawdown se rapproche de la limite.`;
  return <section className="neon-card rounded-3xl border border-violet-400/15 bg-violet-400/[0.04] p-4 sm:p-6"><div className="flex items-start gap-3"><Route className="mt-0.5 h-4 w-4 text-violet-300" /><div><h3 className="text-sm font-semibold text-white">Roadmap stratégique — Trading OS</h3><p className="mt-1 text-xs text-zinc-500">Décision hybride : contexte fondamental, structure technique et historique réel du trader.</p></div></div><div className="mt-5 grid gap-3 md:grid-cols-3"><RoadmapStep label="Fondamental · maintenant" text={fundamentalText} /><RoadmapStep label="Technique · session du jour" text={technicalText} tone="sky" /><RoadmapStep label="Historique · semaine / mois" text={historyText} tone="emerald" /></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><div className="rounded-2xl border border-white/[0.07] bg-black/20 p-4"><p className="text-xs font-semibold text-white">Horizon court terme</p><p className="mt-2 text-xs leading-5 text-zinc-500">Attendre l'alignement événement → niveau technique → risque défini avant l'ordre.</p></div><div className="rounded-2xl border border-white/[0.07] bg-black/20 p-4"><p className="text-xs font-semibold text-white">Horizon semaine / mois</p><p className="mt-2 text-xs leading-5 text-zinc-500">Journaliser la paire, la session et le contexte macro pour améliorer l'espérance sans augmenter mécaniquement le risque.</p></div></div></section>;
}
function RoadmapStep({ label, text, tone = "violet" }: { label: string; text: string; tone?: "violet" | "sky" | "emerald" }) { const colors = { violet: "border-violet-300/15", sky: "border-sky-300/15", emerald: "border-emerald-300/15" }; return <div className={`rounded-2xl border ${colors[tone]} bg-black/20 p-4`}><p className="text-[10px] font-semibold uppercase tracking-wider text-zinc-500">{label}</p><p className="mt-2 text-xs leading-5 text-zinc-400">{text}</p></div>; }

export function TradeTagging({ trades }: { trades: MT5Trade[] }) {
  const [tags, setTags] = useState<Record<string, TradeTag[]>>({});
  const [filter, setFilter] = useState<TradeTag | "all">("all");
  const [selectedTrade, setSelectedTrade] = useState(trades[0]?.ticket ?? "");
  const currentTags = tags[selectedTrade] ?? [];
  const visible = useMemo(() => trades.filter((trade) => filter === "all" || (tags[trade.ticket] ?? []).includes(filter)), [filter, tags, trades]);
  const toggle = (tag: TradeTag) => setTags((previous) => ({ ...previous, [selectedTrade]: currentTags.includes(tag) ? currentTags.filter((item) => item !== tag) : [...currentTags, tag] }));
  return <section className="neon-card rounded-3xl border border-amber-400/15 bg-amber-400/[0.04] p-4 sm:p-6"><div className="flex items-start justify-between gap-3"><div><div className="flex items-center gap-2 text-sm font-semibold text-white"><Tag className="h-4 w-4 text-amber-300" /> Étiquettes comportementales</div><p className="mt-1 text-xs text-zinc-500">Ajoutez des tags légers localement et mesurez leur rentabilité.</p></div><Filter className="h-4 w-4 text-amber-300" /></div><div className="mt-5 grid gap-3 md:grid-cols-[1fr_1fr]"><select value={selectedTrade} onChange={(event) => setSelectedTrade(event.target.value)} className="rounded-xl border border-white/10 bg-black px-3 py-2 text-xs text-white">{trades.map((trade) => <option key={trade.ticket} value={trade.ticket}>#{trade.ticket} · {trade.symbol} · {money(trade.profit)}</option>)}</select><select value={filter} onChange={(event) => setFilter(event.target.value as TradeTag | "all")} className="rounded-xl border border-white/10 bg-black px-3 py-2 text-xs text-white"><option value="all">Tous les tags</option>{TAGS.map((tag) => <option key={tag} value={tag}>{tag}</option>)}</select></div><div className="mt-4 flex flex-wrap gap-2">{TAGS.map((tag) => <button key={tag} type="button" onClick={() => toggle(tag)} className={`rounded-full border px-3 py-1.5 text-xs transition ${currentTags.includes(tag) ? "border-amber-300/40 bg-amber-300/15 text-amber-200" : "border-white/10 text-zinc-500 hover:text-white"}`}>{tag}</button>)}</div><div className="mt-5 divide-y divide-white/[0.06] rounded-2xl border border-white/[0.07]">{visible.slice(0, 8).map((trade) => <div key={trade.ticket} className="flex items-center justify-between gap-3 p-3 text-xs"><span className="text-zinc-400">#{trade.ticket} · {trade.symbol}</span><span className={trade.profit >= 0 ? "text-emerald-300" : "text-rose-300"}>{money(trade.profit)} · {(tags[trade.ticket] ?? []).join(" ") || "Sans tag"}</span></div>)}{!visible.length && <p className="p-4 text-xs text-zinc-500">Aucun trade ne correspond à ce filtre.</p>}</div></section>;
}

export function AuditCard({ metrics }: { metrics: MT5Metrics }) {
  const exportCard = () => { const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="630" viewBox="0 0 1200 630"><rect width="1200" height="630" fill="#09090b"/><rect x="36" y="36" width="1128" height="558" rx="34" fill="#111113" stroke="#10b981" stroke-opacity=".32"/><text x="80" y="108" fill="#10b981" font-family="Arial" font-size="26" font-weight="700">AUDITPROP · TRADING OS</text><text x="80" y="174" fill="#fff" font-family="Arial" font-size="42" font-weight="700">AuditCard de performance</text><text x="80" y="235" fill="#71717a" font-family="Arial" font-size="22">Résumé issu de votre historique importé</text><text x="80" y="370" fill="#71717a" font-family="Arial" font-size="20">WIN RATE</text><text x="80" y="420" fill="#fff" font-family="Arial" font-size="42" font-weight="700">${metrics.winRate.toFixed(1)}%</text><text x="350" y="370" fill="#71717a" font-family="Arial" font-size="20">PROFIT FACTOR</text><text x="350" y="420" fill="#fff" font-family="Arial" font-size="42" font-weight="700">${metrics.profitFactor === null ? "∞" : metrics.profitFactor.toFixed(2)}</text><text x="690" y="370" fill="#71717a" font-family="Arial" font-size="20">PNL NET</text><text x="690" y="420" fill="${metrics.totalPnL >= 0 ? "#34d399" : "#fb7185"}" font-family="Arial" font-size="42" font-weight="700">${escapeXml(money(metrics.totalPnL))}</text><text x="80" y="530" fill="#52525b" font-family="Arial" font-size="18">Partage optimisé pour X · Telegram · Discord</text></svg>`; const blob = new Blob([svg], { type: "image/svg+xml" }); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = "auditprop-auditcard.svg"; link.click(); URL.revokeObjectURL(url); };
  return <section className="neon-card rounded-3xl border border-emerald-400/15 bg-emerald-400/[0.04] p-4 sm:p-6"><div className="flex items-center justify-between gap-3"><div><div className="flex items-center gap-2 text-sm font-semibold text-white"><Sparkles className="h-4 w-4 text-emerald-300" /> AuditCard</div><p className="mt-1 text-xs text-zinc-500">Export AMOLED dynamique avec vos métriques réelles.</p></div><button type="button" onClick={exportCard} className="inline-flex items-center gap-2 rounded-xl bg-emerald-300 px-3 py-2 text-xs font-semibold text-black transition hover:bg-emerald-200"><Download className="h-3.5 w-3.5" /> Exporter l&apos;image</button></div><div className="mt-5 grid grid-cols-3 gap-2 rounded-2xl border border-emerald-400/15 bg-black/50 p-4 text-center"><div><p className="text-[10px] text-zinc-600">Win Rate</p><p className="mt-1 text-xl font-semibold text-white">{metrics.winRate.toFixed(1)}%</p></div><div><p className="text-[10px] text-zinc-600">Profit Factor</p><p className="mt-1 text-xl font-semibold text-white">{metrics.profitFactor === null ? "∞" : metrics.profitFactor.toFixed(2)}</p></div><div><p className="text-[10px] text-zinc-600">PnL net</p><p className={`mt-1 text-xl font-semibold ${metrics.totalPnL >= 0 ? "text-emerald-300" : "text-rose-300"}`}>{money(metrics.totalPnL)}</p></div></div></section>;
}

export function TradingOsSummary({ metrics }: { metrics: MT5Metrics }) { return <div className="rounded-2xl border border-sky-400/15 bg-sky-400/[0.04] p-4"><div className="flex items-center gap-2 text-xs font-semibold text-sky-200"><TrendingUp className="h-4 w-4" /> Trading OS actif</div><p className="mt-2 text-xs leading-5 text-zinc-500">Le cockpit combine décision, contexte et exécution. Le module Prop Firm reste optionnel.</p></div>; }
