import Link from "next/link";
import { Check, Sparkles } from "lucide-react";
import SiteNav from "@/components/site-nav";

const plans = [
  { name: "Audit", price: "0 €", description: "Pour comprendre votre historique sans engagement.", features: ["Import CSV / HTML multi-brokers", "Métriques de risque locales", "Calendrier PnL et heatmap", "Contexte macro live"] },
  { name: "Risk OS", price: "Bientôt", description: "Pour structurer une boucle de décision complète, avec ou sans challenge Prop Firm.", features: ["Diagnostic IA global", "Execution Mapping avancé", "Export PDF professionnel", "Alertes de consistency"] },
];

export default function PricingPage() {
  return <main className="min-h-screen bg-black text-zinc-100"><SiteNav /><div className="mx-auto max-w-5xl px-5 py-16 sm:px-8 sm:py-24"><div className="mx-auto max-w-2xl text-center"><p className="text-xs font-semibold uppercase tracking-[0.24em] text-emerald-300">Pricing</p><h1 className="mt-4 text-4xl font-semibold tracking-tight text-white sm:text-6xl">Un Trading OS lisible, sans surprise.</h1><p className="mt-5 text-sm leading-7 text-zinc-500">Commencez avec vos données réelles. Les métriques de base restent locales, le module Prop Firm est optionnel et aucun abonnement n’est requis pour explorer votre audit.</p></div><div className="mt-12 grid gap-4 md:grid-cols-2">{plans.map((plan, index) => <article key={plan.name} className={`rounded-3xl border p-6 ${index === 0 ? "border-emerald-400/25 bg-emerald-400/[0.05]" : "border-violet-400/20 bg-violet-400/[0.04]"}`}><div className="flex items-center justify-between"><h2 className="text-xl font-semibold text-white">{plan.name}</h2>{index === 1 && <Sparkles className="h-5 w-5 text-violet-300" />}</div><p className="mt-4 text-3xl font-semibold text-white">{plan.price}</p><p className="mt-3 text-sm leading-6 text-zinc-400">{plan.description}</p><ul className="mt-6 space-y-3">{plan.features.map((feature) => <li key={feature} className="flex items-start gap-2 text-sm text-zinc-300"><Check className="mt-0.5 h-4 w-4 shrink-0 text-emerald-300" />{feature}</li>)}</ul><Link href="/" className="mt-8 inline-flex rounded-xl bg-white px-4 py-2.5 text-xs font-semibold text-black transition hover:bg-emerald-200">{index === 0 ? "Lancer un audit" : "Voir la roadmap"}</Link></article>)}</div><p className="mx-auto mt-8 max-w-2xl text-center text-xs leading-5 text-zinc-600">Les fonctionnalités indiquées “Bientôt” ne sont pas présentées comme disponibles. Les résultats passés ne garantissent aucun résultat futur.</p></div></main>;
}
